baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo with Docsy'

[module]
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
